name: Update Other Repositories

on:
  push:
    branches:
      - main

jobs:
  update-repositories:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get latest release tag
        id: get_latest_tag
        run: |
          ls -a
          git describe --tags --abbrev=0
          echo ::set-output name=tag::$(git describe --tags --abbrev=0)

#      - name: Clone repository 1
#        run: |
#          mkdir test
#          git clone \
#            --depth=1 \
#            https://CrazySneeze:${{ secrets.PAT }}@github.com/CrazySneeze/DnD-WebPage.git \
#            test

      - name: Clone repository 1
        uses: actions/checkout@v2
        with:
          repository: CrazySneeze/DnD-WebPage
          path: test
          token: ${{ secrets.PAT }}

      - name: Print latest release tag
        run: |
          echo "Latest release tag ${{ steps.get_latest_tag.outputs.tag }}"
          echo $(git describe --tags --abbrev=0)

      - name: Modify file in repository 1
        run: sed -i "s/This is a test file/This is a test file WORKING${{ steps.get_latest_tag.outputs.tag }}/g" test/test.txt

      - name: Commit changes in repository 1
        run: |
          ls -a
          cd test
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add .
          git commit -m "Update Common Library version to ${{ steps.get_latest_tag.outputs.tag }}"
          git remote set-url origin https://${{ secrets.PAT }}@github.com/CrazySneeze/DnD-WebPage.git
          git push

      - name: Create pull request for repository 1
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Update Common Library version to ${{ steps.get_latest_tag.outputs.tag }}"
          title: "Update Common Library version"
          body: "Automated PR to update Common Library version to ${{ steps.get_latest_tag.outputs.tag }}"
          branch: "update-common-library"
          base: "main"

      # Repeat the above steps for repository 2 and repository 3 as needed.

